# FILE: docker-compose.yml

services:
  app:
    image: php:8.2-fpm
    container_name: academia_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - academia_network
    build:
      context: .
      dockerfile: Dockerfile

  webserver:
    image: nginx:alpine
    container_name: academia_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - academia_network

  db:
    image: mysql:8.0
    container_name: academia_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: academiabd
      MYSQL_USER: academia_user
      MYSQL_PASSWORD: academia_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - academia_network

networks:
  academia_network:
    driver: bridge

volumes:
  mysql_data:
